### ISSUE TITLE
JEI/Quark/Supplementaries Crash

### ISSUE THREAD

**Issue by pskfyi** [Momo-Studios/Cold-Sweat-Rework-Forge#290]
Thank you for this excellent mod. I held off on reporting this issue when I first noticed it in version 2.3-b03a because I believed #267 was the same issue and I saw your comment indicating that it would be fixed in the next update. However testing revealed that my issue has remained after 2 releases, so I have decided to file this report 🫡 

## Environment

**Minecraft version**: 1.20.1
**Mod loader**: Forge
**Cold Sweat versions**: 2.3-b03a, 2.3-b03b, 2.3-b03c

Tested with both REI and JEI.

This has been reproduced in a fresh Minecraft instance containing only the mentioned mods and their dependencies.

## Issue

Quark adds a custom tooltip renderer that gives additional information about the contents of items that act as containers, such as its seed pouch and bundle items, or vanilla shulker boxes.

Supplementaries adds an item called a Sack which also has one of these custom tooltips. In JEI/REI, hovering over a Sack shows 9 empty slots. (Compare to the Shulker box which shows nothing in this circumstance.) Without Cold Sweat this works fine, but with Cold Sweat installed the inventory does not render and instead it triggers an immediate crash to desktop. See crash log below.

Cheating in a Sack with `/give` does not exhibit the same behavior. It's only within JEI/REI that this occurs.

## Crash Log

<details>

```log
[22:22:58] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[?:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?] {}
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:385) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.getTooltipEndIndex(TooltipHandler.java:81) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.addCustomTooltips(TooltipHandler.java:164) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.__TooltipHandler_addCustomTooltips_GatherComponents.invoke(.dynamic) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1059) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.forge.ScreenOverlayImplForge.renderTooltipInner(ScreenOverlayImplForge.java:53) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:328) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.lateRender(ScreenRegistryImpl.java:384) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$6(DefaultScreenOverlayRenderer.java:102) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$2(DefaultScreenOverlayRenderer.java:66) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent(EventHandlerImplClient.java:158) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Foreground.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinEffectsScreen,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinChatClicked,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	... 26 more
[22:22:58] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 42991e4d-b4b0-4597-89f3-34a3b8d98f24
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.
Time: 2024-05-12 22:22:58
Description: Rendering screen
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:385) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.getTooltipEndIndex(TooltipHandler.java:81) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.addCustomTooltips(TooltipHandler.java:164) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.__TooltipHandler_addCustomTooltips_GatherComponents.invoke(.dynamic) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1059) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.forge.ScreenOverlayImplForge.renderTooltipInner(ScreenOverlayImplForge.java:53) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:328) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.lateRender(ScreenRegistryImpl.java:384) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$6(DefaultScreenOverlayRenderer.java:102) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$2(DefaultScreenOverlayRenderer.java:66) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent(EventHandlerImplClient.java:158) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Foreground.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinEffectsScreen,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinChatClicked,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[?:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?] {}
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:385) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.getTooltipEndIndex(TooltipHandler.java:81) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.TooltipHandler.addCustomTooltips(TooltipHandler.java:164) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.client.event.__TooltipHandler_addCustomTooltips_GatherComponents.invoke(.dynamic) ~[ColdSweat-2.3-b03c.jar%23154!/:2.3-b03c] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1059) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.forge.ScreenOverlayImplForge.renderTooltipInner(ScreenOverlayImplForge.java:53) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:328) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:319) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.lateRender(ScreenRegistryImpl.java:384) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$6(DefaultScreenOverlayRenderer.java:102) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$2(DefaultScreenOverlayRenderer.java:66) ~[RoughlyEnoughItems-12.1.725-forge.jar%23157!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent(EventHandlerImplClient.java:158) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Foreground.invoke(.dynamic) ~[architectury-9.2.14-forge.jar%23152!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23125!/:?] {}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinEffectsScreen,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:76) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinChatClicked,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.0-universal.jar%23165!/:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.InventoryScreen
	Mouse location: Scaled: (359, 48). Absolute: (1435.875000, 195.824219)
	Screen size: Scaled: (428, 260). Absolute: (3420, 2080). Scale factor of 8.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[?:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?] {}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['pskfyi'/545, l='ClientLevel', x=-35.34, y=81.00, z=40.41]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,80,48), Section: (at 0,0,0 in -2,5,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 6792 game time, 6792 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[?:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?] {}
```

</details>

**Comment by MikulDev** [comment]
Thanks for the report. This is a similar issue to that, but in a different part of the code. I have this fixed now for the latest version, which I'm planning on releasing in the next day or so

**Comment by BigMartin58** [comment]
Still crashing post-update.

https://mclo.gs/FodMaC9

**Comment by pskfyi** [comment]
@BigMartin58 the latest update was published on the 16th, but the fix we need was committed on the 17th. (https://github.com/Momo-Softworks/Cold-Sweat/commit/aa021583bfb6371210e5a67dba0e67cab130906a) We have to wait for 1 more update.

**Comment by BigMartin58** [comment]
Ah. Ok. Thank you.

**Comment by pskfyi** [comment]
The issue still persists in `2.3-b03e`, but the unpublished `2.3-b03f` posted [here](https://github.com/Momo-Softworks/Cold-Sweat/issues/303#issuecomment-2138601624) DOES work 🥳
